---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  
language: zh-CN
title: 壹帽主页
favicon: https://blog.onehat.cn/favicon.ico
headerStyle: underlined # default style

background:
  image: /images/wallpaper.jpg
  #image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
  hideVersion: true
  
#showStats: true
statusStyle: "dot"
layout:
  Main:
    style: row
    columns: 7
    useEqualHeights: true
    header: false