---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets


- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short     
