---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
    cpu: true
    memory: true

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short     
